language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true