language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

before_deploy:
  - zip -r gemicai-info_${TRAVIS_TAG}.zip dist

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "gemicai-info_${TRAVIS_TAG}.zip"
  skip_cleanup: true
  on:
    tags: true
